from source.reddit import RedditFront
from source.techcrunch import TechCrunchHome
from source.theverge import TheVergeHome
from source.thehustle import TheHustleHome
from source.exame import ExameHome
from source.infomoney import InfoMoneyHome
from source.wired import WiredHome
from source.startups import StartupsHome
from source.fastcompany import FastCompanyHome
